knowledgebase/accounts/urls.py
from django.conf.urls import url
from accounts.views import (logout_page, login_page,
                            operators_list, add_operator,
                            change_operator)


app_name = "accounts"
urlpatterns = [
    url(r'^logout/', logout_page, name="logout"),
    url(r'^login/', login_page, name="login"),
    url(r'^operatorslist/', operators_list, name="operatorslist"),
    url(r'^add/', add_operator, name="add"),
    url(r'^change/(?P<id>[0-9]+)/', change_operator, name="change"),
]

knowledgebase/articles/urls.py
from django.conf.urls import url
from articles.views import (list_of_articles, page_of_articles, new_article,
                           new_article_success, change_article, delete_article)

app_name = 'articles'
urlpatterns = [
    url(r'change/(?P<id>[0-9]+)/', change_article, name='change'),
    url(r'delete/(?P<id>[0-9]+)/', delete_article, name='delete'),
    url(r'new/success/$', new_article_success, name = 'new_article_success'),
    url(r'new/$', new_article, name = 'new'),
    url(r'(?P<id>[0-9]+)/', page_of_articles, name='page'),
    url(r'$', list_of_articles, name='list'),
]

knowledgebase/knowledgebase/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/articles/', permanent=False)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knowledgebase/templates/base.html
<!doctype html>
<html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>{{ header.title }}</title>
      <link href="/static/css/bootstrap.min.css" rel="stylesheet">

      {# for redactor #}

      <link href="/static/redactor/redactor.css" rel="stylesheet">
      <link href="/static/css/style.css" rel="stylesheet">
      <script src="/static/js/jquery-3.3.1.min.js"></script>
      <script src="/static/redactor/jquery.redactor.init.js"></script>
      <script src="/static/redactor/redactor.min.js"></script>
      <script src="/static/redactor/langs/ru.js"></script>

    </head>
    <body>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">База знаний</a>
          </div>
          <ul class="nav navbar-nav">
            <li><a href="{% url 'articles:list' %}">Лента статей</a></li>
            {% if request.user.is_staff %}
                <li><a href="{% url 'accounts:operatorslist' %}">Управление операторами</a></li>
            {% endif %}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if not is_login %}
                <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% else %}
                <p class="navbar-text">{{ user.last_name }} {{ user.first_name }}</p>
                <li><a href="{% url 'articles:new' %}"><span class="glyphicon glyphicon-plus"></span>Создать статью</a></li>
                <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {% block content %}

      {% endblock content %}
    </body>
</html>