knowledgebase/accounts/urls.py
from django.conf.urls import url
from accounts.views import (logout_page, login_page,
                            operators_list, add_operator,
                            change_operator)


app_name = "accounts"
urlpatterns = [
    url(r'^logout/', logout_page, name="logout"),
    url(r'^login/', login_page, name="login"),
    url(r'^operatorslist/', operators_list, name="operatorslist"),
    url(r'^add/', add_operator, name="add"),
    url(r'^change/(?P<id>[0-9]+)/', change_operator, name="change"),
]

knowledgebase/articles/urls.py
from django.conf.urls import url
from articles.views import (list_of_articles, page_of_articles, new_article,
                           new_article_success, change_article, delete_article)

app_name = 'articles'
urlpatterns = [
    url(r'change/(?P<id>[0-9]+)/', change_article, name='change'),
    url(r'delete/(?P<id>[0-9]+)/', delete_article, name='delete'),
    url(r'new/success/$', new_article_success, name = 'new_article_success'),
    url(r'new/$', new_article, name = 'new'),
    url(r'(?P<id>[0-9]+)/', page_of_articles, name='page'),
    url(r'$', list_of_articles, name='list'),
]

knowledgebase/knowledgebase/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/articles/', permanent=False)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knowledgebase/articles/models.py
from django.contrib.auth.models import User
from django.db import models
from redactor.fields import RedactorField

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name = u"Автор"
    )
    title = models.CharField(
        max_length = 250,
        verbose_name = u"Заголовок"
    )
    short_text = models.TextField(
        verbose_name=u"Короткий текст",
        blank=True,
        help_text = u"Этот текст будет виден на главной странице"
    )
    text = RedactorField(
        verbose_name = u"Текст",
        help_text = u"Этот текст будет виден толкьо после перхода на страницу статьи"
    )
    internal = models.BooleanField(
        default = True,
        verbose_name = u"Только для сотрудников"
    )
    datetime_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=u"Время создания"
    )
    datetime_modified = models.DateTimeField(
        auto_now=True,
        verbose_name=u"Время изменения"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = u"Статья"
        verbose_name_plural = u"Статьи"

knowledgebase/articles/forms.py
from django.forms import ModelForm, Textarea, TextInput, BooleanField, CheckboxInput
from articles.models import Article
from redactor.widgets import RedactorEditor


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'short_text', 'text', 'internal']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'short_text': Textarea(attrs={'class': 'form-control', 'rows': 2}),
            'text': RedactorEditor(attrs={'class': 'redactor-box', 'rows': 40}),
            'internal': CheckboxInput(),
        }

knowledgebase/articles/views.py
import json
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from articles.models import Article
from articles.forms import ArticleForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def list_of_articles(request):
    is_login = False
    user = None

    if request.user.is_authenticated():
        articles = Article.objects.all().order_by("-datetime_created")
        is_login = True
        user = request.user
    else:
        articles = Article.objects.filter(
            internal=False
        ).order_by("-datetime_created")

    paginator = Paginator(articles, 5)

    page = request.GET.get('page')

    try:
        articles_p = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles_p = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles_p = paginator.page(paginator.num_pages)

    context = {
        "header": {
            "title": "Лента статей"
        },
        "articles": articles_p,
        "is_login": is_login,
        "user": user
    }
    template = loader.get_template('articles/allarticles.html')
    return HttpResponse(template.render(context, request))


def page_of_articles(request, id):
    is_login = False
    user = None
    views_author = False

    article = get_object_or_404(Article, id = id)
    title = u"Статья {title}".format(title=article.title)

    if request.user.is_authenticated:
        is_login = True
        user = request.user
        views_author = article.author == user
    else:
        if article.internal:
            return HttpResponseForbidden("Доступ запрещён")

    context = {
        "header": {
            "title": title
        },
        "article": article,
        "views_author": views_author,
        "is_login": is_login,
        "user": user
    }
    template = loader.get_template('articles/article.html')
    return HttpResponse(template.render(context, request))


@login_required
def new_article(request):
    is_login = True
    user = request.user

    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = Article.objects.create(
                author = request.user,
                title = form.cleaned_data['title'],
                short_text = form.cleaned_data['short_text'],
                text = form.cleaned_data['text'],
                internal = form.cleaned_data['internal']
            )
            article.save()
            request.session['new_article'] = json.dumps(True)
            request.session['last_created_article'] = json.dumps(article.id)
            return redirect(reverse('articles:new_article_success'))


    form = ArticleForm()
    context = {
        "header": {
            "title": "Создать новую статью"
        },
        "form": form,
        "is_login": is_login,
        "user": user
    }
    template = loader.get_template('articles/newarticle.html')
    return HttpResponse(template.render(context, request))


@login_required
def new_article_success(request):
    new_article_created = False
    is_login = True
    user = request.user

    try:
        new_article_created = json.loads(request.session['new_article'])
        last_created_article_id = json.loads(
            request.session['last_created_article']
        )
    except KeyError:
        pass

    if new_article_created:
        request.session['new_article'] = False
        article = get_object_or_404(Article, id = last_created_article_id)
        context = {
            "article": article,
            "is_login": is_login,
            "user": user
        }
        template = loader.get_template('articles/successcreated.html')
        return HttpResponse(template.render(context, request))
    else:
        return redirect(reverse('articles:new'))


@login_required
def change_article(request, id):
    changed = False
    is_login = True
    user = request.user

    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            id = request.POST["id_article"]
            article = get_object_or_404(Article, id = id)
            article.title = form.cleaned_data["title"]
            article.short_text = form.cleaned_data["short_text"]
            article.text = form.cleaned_data["text"]
            article.internal = form.cleaned_data["internal"]
            article.save()
            changed = True

    if changed:
        article = article
    else:
        article = get_object_or_404(Article, id = id)

    title = u"Изменение статьи {title}".format(title=article.title)
    form = ArticleForm(instance=article)
    context = {
        "header": {
            "title": title,
        },
        "article": article,
        "form": form,
        "changed": changed,
        "is_login": is_login,
        "user": user
    }
    template = loader.get_template('articles/changearticle.html')
    return HttpResponse(template.render(context, request))


@login_required
def delete_article(request, id):
    is_login = True
    user = request.user

    if request.method == 'POST':
        article = get_object_or_404(Article, id = id)
        if user == article.author:
            article.delete()
            context = {
                "header": {
                    "title": "Статья успешно удалена",
                },
                "is_login": is_login,
                "user": user
            }
            template = loader.get_template('articles/successdeleted.html')
            return HttpResponse(template.render(context, request))

knowledgebase/articles/templates/articles/allarticles.html
{% extends 'base.html' %}

{% block content %}
<articles>
  <div class="container">
    <h1>База знаний</h1>
  </div>

  <div class="container">
      {% for article in articles %}
        <div>
          <h3>{{ article.title }}</h3>
          <p>{{ article.datetime_created }}, {{ article.author.get_full_name }}</p>
          <p>{{ article.short_text }}</p>
          <form action="{% url 'articles:page' article.id %}">
              <button type="submit" class="btn btn-primary btn-sm">Читать дальше</button>
          </form>
        </div>
      {% endfor %}
  </div>

  <div class="container">
    <div class="my-pagination">
      {% if articles.has_previous %}
        <a class="pagination-control" href="?page={{ articles.previous_page_number }}">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        </a>
      {% endif %}

      <ul class="pagination">
        {% for i in articles.paginator.page_range %}
          <li {% if i == articles.number %}class="active"{% endif %}><a href="?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
      </ul>

      {% if articles.has_next %}
        <a class="pagination-control" href="?page={{ articles.next_page_number }}">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        </a>
      {% endif %}
    </div>
  </div>

</articles>
{% endblock content %}

knowledgebase/articles/templates/articles/article.html
{% extends 'base.html' %}

{% block content %}
<articles>
  <div class="container">
    <p>{{ article.datetime_created }}, {{ article.author.get_full_name }}</p>
    <h1>{{ article.title }}</h1>
    <div>{{ article.short_text }}</div>
    <br>
    <div>{{ article.text|safe }}</div>
    {% if views_author %}
      <form action="{% url "articles:change" article.id %}">
        <button type="submit" class="btn btn-default">Редактировать статью</button>
      </form>
    {% endif %}
  </div>
</articles>
{% endblock content %}

knowledgebase/articles/templates/articles/changearticle.html
{% extends 'base.html' %}

{% block content %}
  <articles>
    <div class="container">
      {% if changed %}
        <div class="alert alert-success">
          <strong>Успех!</strong> Статья <a href="{% url 'articles:page' article.id %}" class="alert-link">"{{ article.title }}"</a> успешно изменена.
        </div>
      {% endif %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <b>Статья создана:</b> {{ article.datetime_created }}<br>
          <b>Последнее изменение:</b> {{ article.datetime_modified }}
        </div>
        <div class="panel-body">
          <div class="form-group">
            <form action="{% url 'articles:change' article.id %}" method="POST">
              {% csrf_token %}
              <label for="form.title.id">{{ form.title.label }}</label>
              {{ form.title }}
              <label for="form.short_text.id">{{ form.short_text.label }}</label>
              {{ form.short_text }}
              <label for="form.text.id">{{ form.text.label }}</label>
              {{ form.text }}
              <label for="form.internal.id">{{ form.internal.label }}</label>
              {{ form.internal }}
              <input type="hidden" name="id_article" value="{{ article.id }}">
              <button type="Submit" class="btn btn-primary pull-right">Изменить статью</button>
            </form>
            <form action="{% url 'articles:delete' article.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger pull-left">Удалить статью</button>
            </form>
          </div>
        </div>
      </div>

    </div>
  </articles>
{% endblock content %}

knowledgebase/articles/templates/articles/newarticle.html
{% extends 'base.html' %}

{% block content %}
<articles>
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        Создать новую статью
      </div>
      <div class="panel-body">
        <div class="form-group">
          <form action="{% url 'articles:new' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary pull-right">Создать</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</articles>
{% endblock content %}

knowledgebase/articles/templates/articles/successcreated.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Статья успешно создана</h1>
    <p>Вы успешно создали статью: <a href="{% url 'articles:page' article.id %}">{{ article.title }}</a></p>
    <p>
      <a class="btn btn-primary btn-lg" href="{% url "articles:new" %}" role="button">Добавить ещё статью</a>
      <a class="btn btn-primary btn-lg" href="{% url "articles:list" %}" role="button">На главную</a>
    </p>
  </div>
</div>
{% endblock content %}

knowledgebase/articles/templates/articles/successdeleted.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Статья успешно удалена</h1>
    <p>
      <a class="btn btn-primary btn-lg" href="{% url "articles:list" %}" role="button">На главную</a>
    </p>
  </div>
</div>
{% endblock content %}