knowledgebase/accounts/urls.py
from django.conf.urls import url
from accounts.views import (logout_page, login_page,
                            operators_list, add_operator,
                            change_operator)


app_name = "accounts"
urlpatterns = [
    url(r'^logout/', logout_page, name="logout"),
    url(r'^login/', login_page, name="login"),
    url(r'^operatorslist/', operators_list, name="operatorslist"),
    url(r'^add/', add_operator, name="add"),
    url(r'^change/(?P<id>[0-9]+)/', change_operator, name="change"),
]

knowledgebase/knowledgebase/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/articles/', permanent=False)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knowledgebase/accounts/models.py
from django.db import models

# Create your models here.

knowledgebase/accounts/forms.py
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput
from django.contrib.auth.models import User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        widgets = {
            'username': TextInput(attrs={'class': 'form-control', 'required': True}),
            'first_name': TextInput(attrs={'class': 'form-control', 'required': True}),
            'last_name': TextInput(attrs={'class': 'form-control', 'required': True}),
            'email': EmailInput(attrs={'class': 'form-control', 'required': True}),
            'password': PasswordInput(attrs={'class': 'form-control', 'required': True})
        }


class UserChangeForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_active']
        widgets = {
            'username': TextInput(attrs={'class': 'form-control', 'required': True}),
            'first_name': TextInput(attrs={'class': 'form-control', 'required': True}),
            'last_name': TextInput(attrs={'class': 'form-control', 'required': True}),
            'email': EmailInput(attrs={'class': 'form-control', 'required': True}),
        }

    def is_valid(self):
        valid = super(UserChangeForm, self).is_valid()
        return valid

    def clean(self):
        username = self.cleaned_data.get('username')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        email = self.cleaned_data.get('email')
        is_active = self.cleaned_data.get('is_active')

        return self.cleaned_data

knowledgebase/accounts/views.py
import json
from accounts.forms import UserForm, UserChangeForm
from django.urls import reverse
from django.template import loader
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


# Create your views here.
@login_required
def logout_page(request):
    logout(request)
    return redirect("/articles/")


def login_page(request):
    error_login = False
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET.get("next", "/"))
        else:
            error_login = True

    context = {
        "error_login": error_login
    }
    template = loader.get_template('accounts/loginpage.html')
    return HttpResponse(template.render(context, request))


@login_required
@staff_member_required
def operators_list(request):
    is_login = True
    user = request.user
    users = User.objects.filter(is_superuser=False)
    alert = None

    try:
        if json.loads(request.session['user_changed']):
            changed_user = User.objects.get(id = json.loads(request.session['user_changed_id']))
            alert = "Пользователь {userfullname} успешно изменён.".format(userfullname = changed_user.get_full_name())
            request.session['user_changed'] = json.dumps(False)
    except KeyError:
        pass

    try:
        if json.loads(request.session['user_created']):
            created_user = User.objects.get(id = json.loads(request.session['user_created_id']))
            alert = "Пользователь {userfullname} успешно создан.".format(userfullname = created_user.get_full_name())
            request.session['user_created'] = json.dumps(False)
    except KeyError:
        pass

    context = {
        "header": {
            "title": "Список операторов"
        },
        "is_login": is_login,
        "user": user,
        "users": users,
        "alert": alert
    }
    template = loader.get_template('accounts/operatorslist.html')
    return HttpResponse(template.render(context, request))


@login_required
@staff_member_required
def add_operator(request):
    is_login = True
    user = request.user
    form = UserForm()

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(
                username = form.cleaned_data['username'],
                first_name = form.cleaned_data['first_name'],
                last_name = form.cleaned_data['last_name'],
                email = form.cleaned_data['email'],
                password = form.cleaned_data['password'],
            )

            request.session['user_created'] = json.dumps(True)
            request.session['user_created_id'] = json.dumps(new_user.id)

            return redirect("/accounts/operatorslist/")

    context = {
        "header": {
            "title": "Добавить оператора"
        },
        "is_login": is_login,
        "user": user,
        "form": form
    }
    template = loader.get_template('accounts/addaccount.html')
    return HttpResponse(template.render(context, request))


@login_required
@staff_member_required
def change_operator(request, id):
    is_login = True
    user = request.user

    changed_user = User.objects.get(id = int(id))
    form = UserChangeForm(instance=changed_user)

    if request.method == 'POST':
        form = UserChangeForm(request.POST)
        if form.is_valid():
            changed_user.username = form.cleaned_data["username"]
            changed_user.first_name = form.cleaned_data["first_name"]
            changed_user.last_name = form.cleaned_data["last_name"]
            changed_user.email = form.cleaned_data["email"]
            changed_user.is_active = form.cleaned_data["is_active"]
            changed_user.save()

            request.session['user_changed'] = json.dumps(True)
            request.session['user_changed_id'] = json.dumps(changed_user.id)

            return redirect(reverse('accounts:operatorslist'))
    context = {
        "header": {
            "title": "Изменить оператора"
        },
        "is_login": is_login,
        "user": user,
        "form": form,
    }

    template = loader.get_template('accounts/changeoperator.html')
    return HttpResponse(template.render(context, request))

knowledgebase/accounts/templates/accounts/addaccount.html
{% extends 'base.html' %}

{% block content %}
  <articles>
    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading">
          Создать нового пользователя
        </div>
        <div class="panel-body">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary pull-right">Создать</button>
          </form>
        </div>
      </div>
    </div>
  </articles>
{% endblock content %}

knowledgebase/accounts/templates/accounts/changeoperator.html
{% extends 'base.html' %}

{% block content %}
  <articles>
    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading">
          Изменить пользователя
        </div>
        <div class="panel-body">
          <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary pull-right">Изменить</button>
          </form>
        </div>
      </div>
    </div>
  </articles>
{% endblock content %}

knowledgebase/accounts/templates/accounts/loginpage.html
{% extends 'base.html' %}

{% block content %}
  <articles>
    <div class="container">
      {% if error_login %}
      <div class="alert alert-warning">
        <strong>Ошибка!</strong> Попытка входа в систему неудачна.
      </div>
      {% endif %}
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
         <label for="usr">Name:</label>
         <input type="text" class="form-control" id="usr" name="username">
        </div>
        <div class="form-group">
         <label for="pwd">Password:</label>
         <input type="password" class="form-control" id="pwd" name="password">
        </div>
        <button type="submit" class="btn btn-primary pull-right">Вход</button>
      </form>
    </div>
  </articles>
{% endblock content %}

knowledgebase/accounts/templates/accounts/operatorslist.html
{% extends 'base.html' %}

{% block content %}
  <articles>
    <div class="container">
      {% if alert %}
      <div class="alert alert-success">
        <strong>Success!</strong> {{ alert }}
      </div>
      {% endif %}
      <ul class="list-group">
        {% for user in users %}
            <div class="list-group-item">
                <b>Оператор:</b> {% if not user.is_active %}<strike>{{ user.get_full_name }}</strike>{% else %}{{ user.get_full_name }}{% endif %}
                <form class="pull-right" action="{% url 'accounts:change' user.id %}">
                    <button type="submit" class="btn btn-xs btn-primary">Изменить пользователя</button>
                </form>
            </div>
        {% endfor %}
      </ul>
      <form action="{% url 'accounts:add' %}">
        <button type="submit" class="btn btn-primary pull-right">Добавить оператора</button>
      </form>
    </div>
  </articles>
{% endblock content %}